# injector consts
# 05.12.2015 Dmitry Volkov

# parameters ID's

ID_SENSITIVITY = 0

ID_THRESHOLD = 1
ID_POTENTIAL_RELAX_TIME = 2

ID_STRENGTH_MIN = 3
ID_STRENGTH_MAX = 4
ID_STRENGTH_RELAX_TIME = 5

ID_RESOURCE_MAX_BY_STRENGTH = 6

ID_RESISTANCE = 7

ID_SYN_VALUE_MAX = 8
ID_SYN_VALUE_MIN = 9
ID_CONNECTION_RELAX_TIME = 10
