# gui 2.0 keys for settings file
# 21.10.2015 Dmitry Volkov

KEY_SETTINGS_TAB = "SETTINGSTAB"

KEY_BUFFERED_OUTPUT_FLAG = "BUFFEREDFLAG"
KEY_BUFFERED_OUTPUT_VALUE = "BUFFEREDVALUE"

KEY_NEURONS_COUNT = "NEURONSCOUNT"
KEY_ELECTRODES_COUNT = "ELECTRODESCOUNT"
KEY_NEURONS_CONNECTIONS = "NEURONSCONNECTIONS"
KEY_ELECTRODES_CONNECTIONS = "ELECTRODESCONNECTIONS"

KEY_LOAD_NETWORK_COMBOBOX = "LOADCOMBOBOX"
KEY_SAVED_FILE = "SAVEDFILEPATH"
KEY_RESTORE_STATE_FLAG = "RESTORESTATE"
KEY_NEURONS_MATRIX_PATH = "MATRIXPATH"
KEY_ELECTRODES_MATRIX_PATH = "ELECTRODESPATH"