# gui 2.0 def consts
# 20.10.2015 Dmitry Volkov

# Settings window
DEFAULT_SETTINGS_TAB = 0

DEFAULT_BUFFERED_OUTPUT_FLAG = False
DEFAULT_BUFFERED_OUTPUT_VALUE = 50

DEFAULT_NEURONS_COUNT = 1
DEFAULT_ELECTRODES_COUNT = 1
DEFAULT_NEURONS_CONNECTIONS = 0
DEFAULT_ELECTRODES_CONNECTIONS = 0

DEFAULT_LOAD_NETWORK_COMBOBOX = 0
DEFAULT_SAVED_FILE = ""
DEFAULT_RESTORE_STATE_FLAG = True
DEFAULT_NEURONS_MATRIX_PATH = ""
DEFAULT_ELECTRODES_MATRIX_PATH = ""

DEFAULT_NOIZE_TYPE = True
DEFAULT_NOIZE_VAL = 5
