# injector consts
# 05.10.2015 Dmitry Volkov

# parameters injector's ID

# network
_INJECTOR_ID_STIM_CURRENT = 0
_INJECTOR_ID_NOIZE_STIM_CURRENT = 1
_INJECTOR_ID_SYN_STEP = 2

# electrode
_INJECTOR_ID_ELECTRODE_THRESHOLD = 3

# neuron
_INJECTOR_ID_STIM_THRESHOLD = 4
_INJECTOR_ID_BRAKE_THRESHOLD = 5
_INJECTOR_ID_STABILITY_LIMIT = 6
_INJECTOR_ID_STIM_RELAX_TIME = 7
_INJECTOR_ID_STABILITY_RELAX_TIME = 8
_INJECTOR_ID_RESISTANCE = 9
_INJECTOR_ID_RELAXED_STIM = 10
_INJECTOR_ID_RESOURCE_MAX = 11
_INJECTOR_ID_RESOURCE_LIMIT = 12