# injector consts
# 05.10.2015 Dmitry Volkov

# parameters injector's ID

# network
INJECTOR_ID_STIM_CURRENT = 0
INJECTOR_ID_NOIZE_STIM_CURRENT = 1
INJECTOR_ID_SYN_STEP = 2

# electrode
INJECTOR_ID_ELECTRODE_THRESHOLD = 3

# neuron
INJECTOR_ID_STIM_THRESHOLD = 4
INJECTOR_ID_BRAKE_THRESHOLD = 5
INJECTOR_ID_STABILITY_LIMIT = 6
INJECTOR_ID_STIM_RELAX_TIME = 7
INJECTOR_ID_STABILITY_RELAX_TIME = 8
INJECTOR_ID_RESISTANCE = 9
INJECTOR_ID_RELAXED_STIM = 10
INJECTOR_ID_RESOURCE_MAX = 11
INJECTOR_ID_RESOURCE_LIMIT = 12